### ISSUE TITLE
Fails to build after install

### ISSUE THREAD

**Issue by byrnedo** [gmurphey/ember-masonry-grid#1]
Hi, 
Just tried installing this in the root of my ember-cli project,  with `npm install --save-dev ember-masonry-grid` and getting the following when running `ember server`:

```
Path or pattern "bower_components/jquery-masonry/dist/masonry.pkgd.min.js" did not match any files
```

Is there something else I need to do?

Update: 

Surprise, surprise; `bower install jquery-masonry --save` fixed that. Maybe that should be in the readme for idiots like me ? :p

**Comment by gmurphey** [comment]
Sorry you ended up running into this. I've added a blueprint to install the bower dependencies by default, so running `ember install:addon ember-masonry-grid` will setup the addon entirely. Thanks for pointing out the issue!

**Comment by byrnedo** [comment]
No worries, happy to have helped!
