### ISSUE TITLE
Helper issue

### ISSUE THREAD

**Issue by chibipirate** [gmurphey/ember-masonry-grid#19]
I've installed the addon per the directions: running ember install ember-masonry-grid.

My issue is that it's not working as expected, thus I'm getting a strange error which is the following: Uncaught Error: Assertion Failed: A helper named `masonry-grid` could not be found
(from the console)

This is the template I used to test it out:

http://notepad.cc/hijepu57

**Comment by netes** [comment]
@chibipirate did you solve this? I've got the same problem.

**Comment by antulik** [comment]
+1 Have the same problem

**Comment by antulik** [comment]
found this issue https://github.com/ember-cli/ember-cli/issues/2768

**Comment by antulik** [comment]
as a work around I've copied components from `/node_modules/ember-masonry-grid/app/components` to my components folder.

**Comment by Redsandro** [comment]
@antulik did you do anything else besides that?

I'm getting this error:

```
Error: Could not find module `ember-masonry-grid/components/masonry-grid/component` imported from `myproject/components/masonry-grid/component`
```

**Comment by antulik** [comment]
@Redsandro don't know, it's been a while ago and we've removed ember-masonry-grid dependancy since then.

**Comment by Redsandro** [comment]
@antulik I fixed it, had to restart ember :blush: 
Your solution still works. :+1: 

You're no longer sorting masonry-style, or did you find a similar plugin?

**Comment by antulik** [comment]
@Redsandro we are not doing masonry style anymore
