### ISSUE TITLE
Error when used with Ember 2.0 Application

### ISSUE THREAD

**Issue by amarseelam** [gmurphey/ember-masonry-grid#20]
The following error is seen when using this component in a Ember 2.0 application

Uncaught Error: Assertion Failed: Depending on arrays using a dependent key ending with `@each` is no longer supported. Please refactor from `Ember.observer('items.@each', function() {});` to `Ember.observer('items.[]', function() {})`.

Looks like the following line in masonry-grid.js is causing the error.

```
layoutMasonry: Ember['default'].observer('items.@each', function () {....});
```

**Comment by ifiokjr** [comment]
Any pull requests open for this?

**Comment by esbanarango** [comment]
:+1:

**Comment by willian** [comment]
1 month and nothing? Is this project still maintained?
